/**
 * Fetches the list of available classes via GraphQL.
 */
function fetchClasses() {
  try {
    const response = {
      data: {
        courseClasses: {
          edges: [
            {
              node: {
                id: "5df162f6-f4eb-4ef6-bfe7-913a80be9c30",
                schoolId: "76b531d2-420f-48f3-ac3a-43370af0773f",
                gradeId: "aea83b7b-6ca3-4144-824d-bf2d5e05d45f",
                gradeLevel: 5,
                hasAssessmentV2: false,
                testPartInfoV2: [],
                academicCalendar: null,
                group: {
                  id: "5df162f6-f4eb-4ef6-bfe7-913a80be9c30",
                  level: null,
                  members: [
                    "7fd93fb4-4773-4dca-8549-b244a09de3c4",
                    "7e10ebc4-d72d-4090-a9a7-cf38c157b28f",
                    "d0085b58-1fa2-4509-b960-1913e264e1b9",
                    "d68234f3-0002-4f7d-b48e-67818389a433",
                    "debaf829-7dd1-4035-a620-f16d38ddc356",
                  ],
                  __typename: "Group",
                },
                sectionId: "a62b0985-3e7f-40e8-878c-14b319d39e8b",
                subjectCategory: "AI Literacy",
                terms: [],
                material: {
                  curriculum: null,
                  grade: "333938",
                  subject: "963544",
                  year: 2026,
                  instructionalPlanId: null,
                  materialId: "3e0ec2d2-cf2e-4116-a251-cb2d77643133",
                  materialType: "CORE",
                  isExtraCurricular: false,
                  isNcle: true,
                  __typename: "CourseClassMaterial",
                },
                section: {
                  id: "a62b0985-3e7f-40e8-878c-14b319d39e8b",
                  name: "5A",
                  __typename: "Section",
                },
                teachers: [
                  {
                    uuid: "f77ac7dc-610c-45c8-9d80-fd3ca6337daf",
                    firstName: "Rc",
                    lastName: "Test",
                    __typename: "ClassTeacherInfo",
                  },
                ],
                title: "AI Course-5A",
                sourceId: "",
                status: "ACTIVE",
                academicCalendarId: null,
                academicYearId: "b59a9ea9-8ab4-428b-961c-f465cbc91758",
                academicYear: "2026",
                langCode: "en",
                subjectCode: "AI_LITERACY",
                studentsCount: 5,
                settings: {
                  tutorDhabiEnabled: false,
                  languageDirection: "R-T-L",
                  online: true,
                  practice: true,
                  delayedPacing: false,
                  studentProgressView: null,
                  allowEnrollment: true,
                  __typename: "CourseClassSettings",
                },
                autoSync: true,
                students: [
                  {
                    uuid: "7fd93fb4-4773-4dca-8549-b244a09de3c4",
                    avatar: "avatar_00",
                    firstName: "Rc",
                    middleName: "",
                    lastName: "Test",
                    email: "rc-pstd1@test.com",
                    __typename: "Student",
                  },
                  {
                    uuid: "7e10ebc4-d72d-4090-a9a7-cf38c157b28f",
                    avatar: "avatar_00",
                    firstName: "Rc",
                    middleName: "",
                    lastName: "Test",
                    email: "rc-pstd2@test.com",
                    __typename: "Student",
                  },
                  {
                    uuid: "d0085b58-1fa2-4509-b960-1913e264e1b9",
                    avatar: null,
                    firstName: "Rc",
                    middleName: "Test",
                    lastName: "Test",
                    email: "rc-pstd3@test.com",
                    __typename: "Student",
                  },
                  {
                    uuid: "d68234f3-0002-4f7d-b48e-67818389a433",
                    avatar: "avatar_47",
                    firstName: "Rc",
                    middleName: "Test",
                    lastName: "Test",
                    email: "rc-pstd4@test.com",
                    __typename: "Student",
                  },
                  {
                    uuid: "debaf829-7dd1-4035-a620-f16d38ddc356",
                    avatar: null,
                    firstName: "Rc",
                    middleName: "",
                    lastName: "Test",
                    email: "rc-pstd5@test.com",
                    __typename: "Student",
                  },
                ],
                category: null,
                __typename: "CourseClass",
              },
              __typename: "CourseClassEdge",
            },
            {
              node: {
                id: "9b3516c1-c0c1-4cab-b07f-a99ec4f7e85b",
                schoolId: "76b531d2-420f-48f3-ac3a-43370af0773f",
                gradeId: "aea83b7b-6ca3-4144-824d-bf2d5e05d45f",
                gradeLevel: 5,
                hasAssessmentV2: true,
                testPartInfoV2: [],
                academicCalendar: null,
                group: {
                  id: "9b3516c1-c0c1-4cab-b07f-a99ec4f7e85b",
                  level: null,
                  members: [],
                  __typename: "Group",
                },
                sectionId: "a62b0985-3e7f-40e8-878c-14b319d39e8b",
                subjectCategory: "Math",
                terms: [],
                material: {
                  curriculum: "392027",
                  grade: "231997",
                  subject: "963526",
                  year: 2026,
                  instructionalPlanId: null,
                  materialId: "86950bd0-35b5-43d0-ae91-0432eded879b",
                  materialType: "CORE",
                  isExtraCurricular: false,
                  isNcle: false,
                  __typename: "CourseClassMaterial",
                },
                section: {
                  id: "a62b0985-3e7f-40e8-878c-14b319d39e8b",
                  name: "5A",
                  __typename: "Section",
                },
                teachers: [
                  {
                    uuid: "f77ac7dc-610c-45c8-9d80-fd3ca6337daf",
                    firstName: "Rc",
                    lastName: "Test",
                    __typename: "ClassTeacherInfo",
                  },
                ],
                title: "Math",
                sourceId: null,
                status: "ACTIVE",
                academicCalendarId: null,
                academicYearId: "b59a9ea9-8ab4-428b-961c-f465cbc91758",
                academicYear: "2026",
                langCode: "en",
                subjectCode: "MATH",
                studentsCount: 0,
                settings: {
                  tutorDhabiEnabled: false,
                  languageDirection: "R-T-L",
                  online: true,
                  practice: true,
                  delayedPacing: false,
                  studentProgressView: null,
                  allowEnrollment: true,
                  __typename: "CourseClassSettings",
                },
                autoSync: true,
                students: [],
                category: null,
                __typename: "CourseClass",
              },
              __typename: "CourseClassEdge",
            },
          ],
          pageInfo: {
            hasNextPage: false,
            hasPreviousPage: false,
            startCursor: "5df162f6-f4eb-4ef6-bfe7-913a80be9c30",
            endCursor: "28150452-505e-4a1e-b461-4ecb440fa7e8",
            __typename: "PageInfo",
          },
          currentPageNumber: 0,
          __typename: "CourseClassConnection",
        },
      },
    };

    return response.data.courseClasses.edges.map((edge) => edge.node);
  } catch (error) {
    console.error("GraphQL fetch failed:", error);
    return []; // Return an empty array on failure to prevent UI crashes
  }
}
